# Generated by Django 4.2 on 2025-01-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_productvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
