# Generated by Django 4.2 on 2025-01-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_cart_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='vendor',
        ),
    ]
