# Generated by Django 4.2 on 2025-01-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpayorder',
            name='unique_order_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
