# Generated by Django 4.2 on 2025-01-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order',
            field=models.OneToOneField(blank=True, help_text='Link to the Razorpay order for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payment_app.razorpayorder'),
        ),
    ]
