# Generated by Django 4.2 on 2025-01-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_vendor_product_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
