# Generated by Django 4.2 on 2025-01-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unique_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
